
--#COURSE TABLE
SET NAMES utf8;


--#LESSON TABLE
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('25', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '5', '01 Intro', 'transcription', 'https://www.youtube.com/watch?v=80zkdQJ2y4c', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('26', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '8', '02 Servicio Rest Hola Mundo', 'transcription', 'https://www.youtube.com/watch?v=U_rPO2ILMFU', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('27', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '13', '03 Microservicio Product y JPA', 'transcription', 'https://www.youtube.com/watch?v=0crp-uwM5Fo', '1');|
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('28', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '8', '04 Test JPA', 'transcription', 'https://www.youtube.com/watch?v=owftuXhx_V8', '1');

INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('29', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '6', '05 Service', 'transcription', 'https://www.youtube.com/watch?v=ag92DYmen84', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('30', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '9', '06 Test unitario lógica de negocio', 'transcription', 'https://www.youtube.com/watch?v=VHJUGUgYJ5A', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('31', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '10', '07 REST - Parte 01', 'transcription', 'https://www.youtube.com/watch?v=p5uMy2DLE7A', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('32', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '14', '08 REST - Parte 02', 'transcription', 'https://www.youtube.com/watch?v=V4ClP2wze9g', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('33', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '10', '09 REST - Parte 03', 'https://www.youtube.com/watch?v=BZl4_LuYhm4', '1');

INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('34', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '7', '10 Customer Service', 'transcription', 'https://www.youtube.com/watch?v=iES9XBCApn4', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('35', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '4', '11 Shopping Service', 'transcription', 'https://www.youtube.com/watch?v=P6vrSi6L3Gs', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('36', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '16', '12 Config Server', 'transcription', 'https://www.youtube.com/watch?v=ydtswONk9TE', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('37', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '12', '13 #Eureka Server', 'transcription', 'https://www.youtube.com/watch?v=lJ3-VPzhrFY', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('38', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '22', '14 #Feign', 'transcription', 'https://www.youtube.com/watch?v=JkwDJCBJhis', '1');

INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('40', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '13', '15 #Hystrix', 'transcription', 'https://www.youtube.com/watch?v=JvjDoGPXu9E', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('41', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '13', '16 #gateway', 'transcription', 'https://www.youtube.com/watch?v=0N59T8blTkQ', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('42', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '16', '17 #actuator & #admin', 'transcription', 'https://www.youtube.com/watch?v=LUpUg6NUQ2I', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('43', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '6', '18 #sleuth', 'transcription', 'https://www.youtube.com/watch?v=weRZIwBCGqg', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('44', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud.', '9', '19 #springboot 2.3.2', 'transcription', 'https://www.youtube.com/watch?v=ZJZkUK6Rkl0|', '1');




INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('1', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Componentes, State, JSX', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('2', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Crea una app con React usando create-react-app', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('3', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Componentes, State, JSX', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('4', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Creando Custom Hooks y usando Context para conseguir un estado global en ReactJS', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('4', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Lazy Load, Suspense y paginación con React', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('5', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'CSS Grid, Infinite Scroll y Tests en nuestra app de React', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('6', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Cómo usar React.memo, mejorar el rendimiento y hacer deploy con Vercel de nuestra app de React', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('7', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'SEO con React y Deploy integrado con GitHub', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('8', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'useReducer y tests de hooks con react-hooks-testing-library', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('9', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Login y Sesión de Usuarios 🔐 para guardar Favoritos ⚛️', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('10', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Registro de usuario con Formik, React.createPortal y gestión de favoritos en nuestra app de ReactJS', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('11', 'Síguenos.https://www.mitocode.com', '10', '1 Introducción a la programación Reactiva', '', 'https://www.youtube.com/watch?v=UMgaV9fhLm8', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('12', 'Síguenos.https://www.mitocode.com', '7', '2 Método Subscribe', '', 'https://www.youtube.com/watch?v=dbNBJbAn4Ws', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('13', 'Síguenos.https://www.mitocode.com', '2', '3 Método doOnNext', '', 'https://www.youtube.com/watch?v=qLvG3w7YA5Q', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('14', 'Síguenos.https://www.mitocode.com', '5', '4 Mono y Flux', '', 'https://www.youtube.com/watch?v=jJeYYiqhOTg', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('15', 'Síguenos.https://www.mitocode.com', '6', '5 Operadores de creación', '', 'https://www.youtube.com/watch?v=ackRqg1F2Qs', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('16', 'Síguenos.https://www.mitocode.com', '8', '6 Operadores de Transformación', '', 'https://www.youtube.com/watch?v=yZGrmg-2-qQ', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('17', 'Síguenos.https://www.mitocode.com', '6', '7 Operadores de Filtrado', '', 'https://www.youtube.com/watch?v=k1S0Zz5CKKg', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('18', 'Síguenos.https://www.mitocode.com', '7', '8 Operadores de combinación', '', 'https://www.youtube.com/watch?v=89tks2M46uY', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('19', 'Síguenos.https://www.mitocode.com', '7', '9 Operadores para control de errores', '', 'https://www.youtube.com/watch?v=1So53aWJ9fE', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('20', 'Síguenos.https://www.mitocode.com', '6', '10 Operadores condicionales', '', 'https://www.youtube.com/watch?v=rfgiW1UgqhY', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('21', 'Síguenos.https://www.mitocode.com', '6', '11 Operadores matemáticos', '', 'https://www.youtube.com/watch?v=CMCv5HnDLk8', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('22', 'Síguenos.https://www.mitocode.com', '12', '12 WebFlux', '', 'https://www.youtube.com/watch?v=LpI0FyVyRpI', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('23', 'Síguenos.https://www.mitocode.com', '3', '13 Despliegue en Heroku', '', 'https://www.youtube.com/watch?v=X3vzplcgEpE', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('24', 'Síguenos.https://www.mitocode.com', '4', '14 Spring Reactivo', '', 'https://www.youtube.com/watch?v=JcU03YBTBJ4', '2');
