
--#COURSE TABLE

INSERT INTO `railway`.`courses` (`id`, `category`, `description`, `difficulty`, `image_url`, `title`, `total_duration`) VALUES ('1', 'BACK_END', 'En este curso vas aprender a implementar una arquitectura de microservicios con Spring boot y Spring Cloud. Desarrollaremos paso a paso un sistema de ventas online aplicando la arquitectura de microservicios.', 'INTERMEDIATE', 'https://pbs.twimg.com/profile_images/1235868806079057921/fTL08u_H_400x400.png', 'Curso Microservicios con Spring Boot y Spring Cloud', '5');
INSERT INTO `railway`.`courses` (`id`, `category`, `description`, `difficulty`, `image_url`, `title`, `total_duration`) VALUES ('2', 'BACK_END', 'En este curso aprenderas los conceptos de la programacion reactiva y lograras crear un proyecto para practicar tus conocimientos', 'INTERMEDIATE', 'https://media.licdn.com/dms/image/C4E0BAQHS699MLBiLCA/company-logo_200_200/0/1544496438086?e=2147483647&v=beta&t=hGAn69OIEbyc6jA_1N8Z-gJvNiKasxeUSZmZ5nJHRYA', 'Curso de Programacion Reactiva', '2');
INSERT INTO `railway`.`courses` (`id`, `category`, `description`, `difficulty`, `image_url`, `title`, `total_duration`) VALUES ('3', 'FRONT_END', 'Curso completo de React desde 0', 'BASIC', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fm.youtube.com%2Fc%2Fmidudev&psig=AOvVaw050R4RSyL2j4Qi-Q44TXS4&ust=1677678274790000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCOjm1N6suP0CFQAAAAAdAAAAABAJ', 'Curso REACT JS ⚛️ - Aprende desde CERO 📈 Componentes, State, JSX (Tutorial Desde Cero en Español)', '25');



--#LESSON TABLE
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('25', 'description', '5', '01 Intro', 'transcription', 'https://www.youtube.com/watch?v=80zkdQJ2y4c&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=2', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('26', 'description', '8', '02 Servicio Rest Hola Mundo', 'transcription', 'https://www.youtube.com/watch?v=U_rPO2ILMFU&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=3', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('27', 'description', '13', '03 Microservicio Product y JPA', 'transcription', 'https://www.youtube.com/watch?v=0crp-uwM5Fo&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=4', '1');|
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('28', 'description', '8', '04 Test JPA', 'transcription', 'https://www.youtube.com/watch?v=owftuXhx_V8&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=5', '1');

INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('29', 'description', '6', '05 Service', 'transcription', 'https://www.youtube.com/watch?v=ag92DYmen84&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=6', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('30', 'description', '9', '06 Test unitario lógica de negocio', 'transcription', 'https://www.youtube.com/watch?v=VHJUGUgYJ5A&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=7', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('31', 'description', '10', '07 REST - Parte 01', 'transcription', 'https://www.youtube.com/watch?v=p5uMy2DLE7A&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=8', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('32', 'description', '14', '08 REST - Parte 02', 'transcription', 'https://www.youtube.com/watch?v=V4ClP2wze9g&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=9', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('33', 'description', '10', '09 REST - Parte 03', 'https://www.youtube.com/watch?v=BZl4_LuYhm4&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=10', '1');

INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('34', 'description', '7', '10 Customer Service', 'transcription', 'https://www.youtube.com/watch?v=iES9XBCApn4&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=11', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('35', 'description', '4', '11 Shopping Service', 'transcription', 'https://www.youtube.com/watch?v=P6vrSi6L3Gs&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=12', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('36', 'description', '16', '12 Config Server', 'transcription', 'https://www.youtube.com/watch?v=ydtswONk9TE&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=13', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('37', 'description', '12', '13 #Eureka Server', 'transcription', 'https://www.youtube.com/watch?v=lJ3-VPzhrFY&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=14', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('38', 'description', '22', '14 #Feign', 'transcription', 'https://www.youtube.com/watch?v=JkwDJCBJhis&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=15', '1');

INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('40', 'description', '13', '15 #Hystrix', 'transcription', 'https://www.youtube.com/watch?v=JvjDoGPXu9E&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=16', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('41', 'description', '13', '16 #gateway', 'transcription', 'https://www.youtube.com/watch?v=0N59T8blTkQ&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=17', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('42', 'description', '16', '17 #actuator & #admin', 'transcription', 'https://www.youtube.com/watch?v=LUpUg6NUQ2I&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=18', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('43', 'description', '6', '18 #sleuth', 'transcription', 'https://www.youtube.com/watch?v=weRZIwBCGqg&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=19', '1');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('44', 'description', '9', '19 #springboot 2.3.2', 'transcription', 'https://www.youtube.com/watch?v=ZJZkUK6Rkl0&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=20', '1');




INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('1', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Componentes, State, JSX', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('2', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Crea una app con React usando create-react-app', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('3', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Componentes, State, JSX', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('4', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Creando Custom Hooks y usando Context para conseguir un estado global en ReactJS', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('4', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Lazy Load, Suspense y paginación con React', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('5', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'CSS Grid, Infinite Scroll y Tests en nuestra app de React', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('6', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Cómo usar React.memo, mejorar el rendimiento y hacer deploy con Vercel de nuestra app de React', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('7', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'SEO con React y Deploy integrado con GitHub', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('8', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'useReducer y tests de hooks con react-hooks-testing-library', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('9', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Login y Sesión de Usuarios 🔐 para guardar Favoritos ⚛️', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('10', 'Te enseño React desde cero. 👨‍🏫 ¿Qué es React? ¿Por qué deberías aprenderlo? ¿Por qué lo necesitamos? ¿Qué es JSX 🤔? Props y State. Eventos. Renderizado condicional y useState. 🔥', '2', 'Registro de usuario con Formik, React.createPortal y gestión de favoritos en nuestra app de ReactJS', '¡No olvides suscribirte para próximos vídeos! https://www.youtube.com/c/midudev?sub...', 'https://www.youtube.com/watch?v=T_j60n1zgu0&list=PLV8x_i1fqBw0B008sQn79YxCjkHJU84pC&ab_channel=midudev', '3');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('11', 'Síguenos.https://www.mitocode.com', '10', '1 Introducción a la programación Reactiva', '', 'https://www.youtube.com/watch?v=UMgaV9fhLm8&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('12', 'Síguenos.https://www.mitocode.com', '7', '2 Método Subscribe', '', 'https://www.youtube.com/watch?v=dbNBJbAn4Ws&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=2&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('13', 'Síguenos.https://www.mitocode.com', '2', '3 Método doOnNext', '', 'https://www.youtube.com/watch?v=qLvG3w7YA5Q&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=3&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('14', 'Síguenos.https://www.mitocode.com', '5', '4 Mono y Flux', '', 'https://www.youtube.com/watch?v=jJeYYiqhOTg&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=4&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('15', 'Síguenos.https://www.mitocode.com', '6', '5 Operadores de creación', '', 'https://www.youtube.com/watch?v=ackRqg1F2Qs&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=5&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('16', 'Síguenos.https://www.mitocode.com', '8', '6 Operadores de Transformación', '', 'https://www.youtube.com/watch?v=yZGrmg-2-qQ&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=6&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('17', 'Síguenos.https://www.mitocode.com', '6', '7 Operadores de Filtrado', '', 'https://www.youtube.com/watch?v=k1S0Zz5CKKg&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=7&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('18', 'Síguenos.https://www.mitocode.com', '7', '8 Operadores de combinación', '', 'https://www.youtube.com/watch?v=89tks2M46uY&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=8&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('19', 'Síguenos.https://www.mitocode.com', '7', '9 Operadores para control de errores', '', 'https://www.youtube.com/watch?v=1So53aWJ9fE&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=9&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('20', 'Síguenos.https://www.mitocode.com', '6', '10 Operadores condicionales', '', 'https://www.youtube.com/watch?v=rfgiW1UgqhY&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=10&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('21', 'Síguenos.https://www.mitocode.com', '6', '11 Operadores matemáticos', '', 'https://www.youtube.com/watch?v=CMCv5HnDLk8&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=11&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('22', 'Síguenos.https://www.mitocode.com', '12', '12 WebFlux', '', 'https://www.youtube.com/watch?v=LpI0FyVyRpI&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=12&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('23', 'Síguenos.https://www.mitocode.com', '3', '13 Despliegue en Heroku', '', 'https://www.youtube.com/watch?v=X3vzplcgEpE&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=13&ab_channel=MitoCode', '2');
INSERT INTO `railway`.`lessons` (`id`, `description`, `duration`, `title`, `transcription`, `url_video`, `course_id`) VALUES ('24', 'Síguenos.https://www.mitocode.com', '4', '14 Spring Reactivo', '', 'https://www.youtube.com/watch?v=JcU03YBTBJ4&list=PLvimn1Ins-41pwh18gh_ZkxPOkrEEhXz6&index=14&ab_channel=MitoCode', '2');
